spring.application.name=PathSudhaar
server.port=8081
# Enable H2 Console so you can see the database at http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Database Connection Settings
spring.datasource.url=jdbc:h2:mem:pathsudhaar
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Automatically create tables based on your Java code
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.file.name=logs/path-sudhaar.log